services:
  ingress:
    image: ${INGRESS_IMAGE_NAME}
    container_name: ingress
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    volumes:
     - ./docker-compose-ingress-nginx/templates:/etc/nginx/templates
     - ./docker-compose-ingress-nginx/ssl:/etc/nginx/ssl
    ports:
     - '80:80'
     - "443:443"
    environment:
      - NGINX_HOST=${HOST}
    networks:
      - option_volatility_dashboard

  frontend:
    image: ${FRONTEND_RUNTIME_IMAGE_NAME}
    container_name: frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - option_volatility_dashboard

  backend:
    image: ${BACKEND_RUNTIME_IMAGE_NAME}
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - option_volatility_dashboard

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.112.0
    container_name: victoriametrics
    restart: unless-stopped
    volumes:
     - ./data/victoria-metrics-data:/victoria-metrics-data
     - ./scrape.yaml:/scrape.yaml
    ports:
     - "8428:8428"
    command:
      - "-storageDataPath=/victoria-metrics-data"
      - "-httpListenAddr=:8428"
      - "-retentionPeriod=2d"
      - "-promscrape.config=/scrape.yaml"
    networks:
      - option_volatility_dashboard

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./data/grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=https://localhost/grafana
      - GF_INSTALL_PLUGINS=victoriametrics-metrics-datasource
    depends_on:
      - victoriametrics
    networks:
      - option_volatility_dashboard

networks:
  option_volatility_dashboard:
