services:
  backend:
    image: shadrinsergey/option_volatility_dashboard:0.0.1
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - option_volatility_dashboard

networks:
  option_volatility_dashboard:
    external: true
    name: option_volatility_dashboard
