services:
  ingress:
    image: nginx:1.25.5-bookworm
    container_name: ingress
    restart: unless-stopped
    volumes:
     - ./templates:/etc/nginx/templates
     - ./ssl:/etc/nginx/ssl
     - ./letsencrypt/html:/letsencrypt/html
    ports:
     - '80:80'
     - "443:443"
    env_file: ".env"
    networks:
      - option_volatility_dashboard

networks:
  option_volatility_dashboard:
    external: true
    name: option_volatility_dashboard
