---
- name: Deploy App
  hosts: all
  become: yes

  vars:
    local_dir: "../app/{{ app }}"
    remote_dir: "/opt/option_volatility_dashboard/{{ app }}"

  tasks:
    - name: Create {{ app }} directory
      file:
        path: "{{ remote_dir }}"
        state: directory
        mode: '0755'

    - name: Copy files
      copy:
        src: "{{ local_dir }}/{{ item }}"
        dest: "{{ remote_dir }}/{{ item }}"
        mode: '0644'
      loop: "{{ copy_paths }}"

    - name: Run Docker Compose
      shell: |
        cd {{ remote_dir }} && \
        docker compose pull && \
        docker compose down -t 1 && \
        docker compose up -d
      register: compose_result
      changed_when: "'Creating' in compose_result.stdout or 'Pulling' in compose_result.stdout"

    - name: Show compose output
      debug:
        var: compose_result.stdout_lines