name: Build and deploy backend app
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'app/backend/src/**'
jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-app.yml
    with:
      app: "backend"