name: Build app
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shadrinsergey
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build runtime docker image ${{ inputs.app }}
        run: ./bin/build-runtime-image.sh ${{ inputs.app }}

      - name: Push runtime docker image ${{ inputs.app }}
        run: ./bin/push-runtime-image.sh ${{ inputs.app }}