name: Build and deploy app
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
jobs:
  call-build:
    uses: ./.github/workflows/build-app.yml
    with:
      app: "${{ inputs.app }}"
    secrets: inherit

  call-deploy:
    needs: call-build
    uses: ./.github/workflows/deploy-app.yml
    with:
      app: "${{ inputs.app }}"
    secrets: inherit