name: Build and deploy app
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: shadrinsergey
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build runtime docker image ${{ inputs.app }}
        run: ./bin/build-runtime-image.sh ${{ inputs.app }}

      - name: Push runtime docker image ${{ inputs.app }}
        run: ./bin/push-runtime-image.sh ${{ inputs.app }}

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Display Ansible version
        run: ansible --version

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: ansible/deploy-app-playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --user "${{ secrets.REMOTE_USER }}"
            --inventory "${{ secrets.REMOTE_HOST }},"
            --extra-vars "app=${{ inputs.app }}"
            --verbose