name: Build and deploy frontend
on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'app/frontend/src/**'
      - 'app/frontend/docker-compose.yml'
jobs:
  call-build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-app.yml
    with:
      app: "frontend"
    secrets: inherit